SELECT  A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CRAETED_DATE
  FROM  USED_GOODS_BOARD AS A
 INNER JOIN  USED_GOODS_REPLY AS B
ON  A.BOARD_ID = B.BOARD_ID
 WHERE SUBSTR(A.CREATED_DATE,1,7) = '2022-10'
 ORDER BY  B.CREATED_DATE, A.TITLE;

# select a.TITLE, 
#     a.BOARD_ID, 
#     b.REPLY_ID, 
#     a.WRITER_ID, 
#     a.CONTENTS, 
#     date_format(b.CREATED_DATE, '%Y-%m-$d') as CREATED_DATE
# from USED_GOODS_BOARD as a
# inner join USED_GOODS_REPLY as b
# on a.BOARD_ID = b.BOARD_ID
# where substr(a.CREATED_DATE,1,7) = '2022-10'
# order by b.CREATED_DATE, a.TITLE;